#ifndef CONSTANTS_H
#define CONSTANTS_H 

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define PLAYER_OFFSET_LEFT 100
#define GROUND_HEIGHT 100
#define PLAYER_SIZE 40
#define JUMP_SPEED 1
#define MIN_BOX_OFFSET_LEFT 400
#define GRAVITY 0.5
#define BOX_SPEED 0.1

#endif
